### ISSUE TITLE
Compilation does not generate executable

### ISSUE THREAD

**Issue by fabiopavan** [pmq20/ruby-packer#90] opened 2020-03-03 01:50 UTC
```
C:\Users\Romeu>rubyc -o C:\Users\Romeu\Desktop\corax.exe -r C:\Users\Romeu\Desktop\Corax
C:/__enclose_io_memfs__/local/lib/compiler.rb:71: [BUG] Segmentation fault
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mswin64_140]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0032 e:000031 CFUNC  :write
c:0005 p:---- s:0029 e:000028 CFUNC  :puts
c:0004 p:0152 s:0024 e:000023 METHOD C:/__enclose_io_memfs__/local/lib/compiler.rb:71 [FINISH]
c:0003 p:---- s:0018 e:000017 CFUNC  :new
c:0002 p:0153 s:0012 E:0008d0 EVAL   /__enclose_io_memfs__/local/bin/rubyc:148 [FINISH]
c:0001 p:0000 s:0003 E:001b70 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/__enclose_io_memfs__/local/bin/rubyc:148:in `<main>'
/__enclose_io_memfs__/local/bin/rubyc:148:in `new'
C:/__enclose_io_memfs__/local/lib/compiler.rb:71:in `initialize'
C:/__enclose_io_memfs__/local/lib/compiler.rb:71:in `puts'
C:/__enclose_io_memfs__/local/lib/compiler.rb:71:in `write'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0x14) [0x00007FF8F88FC144]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x93) [0x00007FF8F5878BA3]
 [0x00007FF791D83934]
 [0x00007FF791D839B9]
 [0x00007FF791CBAE40]
 [0x00007FF791D25026]
C:\WINDOWS\System32\ucrtbase.dll(seh_filter_exe+0x233) [0x00007FF8F67CC043]
 [0x00007FF791DFCB00]
C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll(_C_specific_handler+0xa0) [0x00007FF8E497C1C0]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x11f) [0x00007FF8F890121F]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlRaiseException+0x399) [0x00007FF8F88CA289]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007FF8F88FFE8E]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlDllShutdownInProgress+0xc6) [0x00007FF8F88672A6]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x1f6) [0x00007FF8F887B5F6]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlEnterCriticalSection+0x40) [0x00007FF8F887B440]
 [0x00007FF791C7AC46]
 [0x00007FF791C6354C]
 [0x00007FF791CDE9DD]
 [0x00007FF791CDE856]
 [0x00007FF791CDF202]
 [0x00007FF791CE09EF]
 [0x00007FF791CB01A1]
 [0x00007FF791CB0002]
 [0x00007FF791CAFCCA]
 [0x00007FF791CAA656]
 [0x00007FF791CAB511]
 [0x00007FF791CE5AB8]
 [0x00007FF791CB0545]
 [0x00007FF791CB1029]
 [0x00007FF791CB0C4D]
 [0x00007FF791CB3886]
 [0x00007FF791CB25C1]
 [0x00007FF791CAFF36]
 [0x00007FF791CAFCCA]
 [0x00007FF791CAA656]
 [0x00007FF791CAB511]
 [0x00007FF791CCB274]
 [0x00007FF791CB0545]
 [0x00007FF791CB1029]
 [0x00007FF791CB0C4D]
 [0x00007FF791CB3886]
 [0x00007FF791CB25C1]
 [0x00007FF791C5EA5F]
 [0x00007FF791C5EAB9]
 [0x00007FF791C5ED30]
 [0x00007FF791C5111C]
 [0x00007FF791DFBE59]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007FF8F8547BD4]

-- Other runtime information -----------------------------------------------

* Loaded script: /__enclose_io_memfs__/local/bin/rubyc

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 encdb.so
    5 trans/transdb.so
    6 enc/windows_1252.so
    7 C:/__enclose_io_memfs__/lib/ruby/2.4.0/unicode_normalize.rb
    8 C:/__enclose_io_memfs__/lib/ruby/2.4.0/x64-mswin64_140/rbconfig.rb
    9 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/compatibility.rb
   10 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/defaults.rb
   11 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/deprecate.rb
   12 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/errors.rb
   13 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/version.rb
   14 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/requirement.rb
   15 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/platform.rb
   16 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/basic_specification.rb
   17 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/stub_specification.rb
   18 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/util/list.rb
   19 stringio.so
   20 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/specification.rb
   21 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/exceptions.rb
   22 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   23 C:/__enclose_io_memfs__/lib/ruby/2.4.0/monitor.rb
   24 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   25 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems.rb
   26 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/dependency.rb
   27 C:/__enclose_io_memfs__/lib/ruby/2.4.0/rubygems/path_support.rb
   28 C:/__enclose_io_memfs__/lib/ruby/2.4.0/fileutils.rb
   29 C:/__enclose_io_memfs__/local/lib/compiler/constants.rb
   30 C:/__enclose_io_memfs__/local/lib/compiler/error.rb
   31 C:/__enclose_io_memfs__/lib/ruby/2.4.0/shellwords.rb
   32 C:/__enclose_io_memfs__/lib/ruby/2.4.0/tmpdir.rb
   33 C:/__enclose_io_memfs__/lib/ruby/2.4.0/open3.rb
   34 C:/__enclose_io_memfs__/local/lib/compiler/utils.rb
   35 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/version.rb
   36 C:/__enclose_io_memfs__/lib/ruby/2.4.0/ostruct.rb
   37 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/generic_object.rb
   38 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/common.rb
   39 json/ext/parser.so
   40 json/ext/generator.so
   41 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json/ext.rb
   42 C:/__enclose_io_memfs__/lib/ruby/2.4.0/json.rb
   43 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc2396_parser.rb
   44 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/rfc3986_parser.rb
   45 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/common.rb
   46 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/generic.rb
   47 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ftp.rb
   48 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/http.rb
   49 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/https.rb
   50 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldap.rb
   51 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/ldaps.rb
   52 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri/mailto.rb
   53 C:/__enclose_io_memfs__/lib/ruby/2.4.0/uri.rb
   54 date_core.so
   55 C:/__enclose_io_memfs__/lib/ruby/2.4.0/date.rb
   56 C:/__enclose_io_memfs__/lib/ruby/2.4.0/time.rb
   57 C:/__enclose_io_memfs__/lib/ruby/2.4.0/open-uri.rb
   58 C:/__enclose_io_memfs__/local/lib/compiler/gem_package.rb
   59 pathname.so
   60 C:/__enclose_io_memfs__/lib/ruby/2.4.0/pathname.rb
   61 C:/__enclose_io_memfs__/local/lib/compiler.rb
   62 C:/__enclose_io_memfs__/lib/ruby/2.4.0/optparse.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

I wrote the command above and got the following result. It did not generate any executable called corax.exe in my computer and it seems to not be compiling my script, but other things.

**Comment by ekuiter** [comment] 2020-06-02 05:39
I get the same error, even when only running `rubyc`.

**Comment by ekuiter** [comment] 2020-06-02 15:04
(possibly duplicate of #83)

**Comment by pmq20** [comment] 2020-06-27 21:54
Sorry for such an obvious failure! I'll close this issue and post progresses in #83

**Closed by pmq20** 2020-06-27 21:54 UTC
