### ISSUE TITLE
Not Finding bundler gem in build?

### ISSUE THREAD

**Issue by ddoherty03** [pmq20/ruby-packer#11] opened 2017-07-22 17:57 UTC
In trying to compile cli gem I am working on with:

```shell
rubyc bin/byr
```
I get the following error at the end:

```
-> Running [{"CI"=>"true", "PATH"=>"/tmp/rubyc/ruby/build/bin:/home/ded/.rbenv/shims:/home/ded/.rbenv/bin:/home/ded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ded/.cask/bin:/home/ded/go/bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "sh", "-c", "gem install /__enclose_io_memfs__/local/vendor/bundler-1.15.1.gem --force --local --no-rdoc --no-ri"]
ERROR:  Could not find a valid gem '/__enclose_io_memfs__/local/vendor/bundler-1.15.1.gem' (>= 0) in any repository
Failed running [{"CI"=>"true", "PATH"=>"/tmp/rubyc/ruby/build/bin:/home/ded/.rbenv/shims:/home/ded/.rbenv/bin:/home/ded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ded/.cask/bin:/home/ded/go/bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "sh", "-c", "gem install /__enclose_io_memfs__/local/vendor/bundler-1.15.1.gem --force --local --no-rdoc --no-ri"]
```
It looks like it is trying to install the bundler gem from a local source but not finding it.  Also seems to specify a root path /__enclose_io_memfs__ ...

Am I missing something obvious here, or is this a bug?

**Comment by pmq20** [comment] 2017-07-27 13:29
Could you share the code of `bin/byr` so that I can reproduce it locally? Otherwise I will try a random CLI gem project with Gemfile to see if I can reproduce it. Thanks!

**Comment by pmq20** [comment] 2017-07-28 02:31
@ddoherty03 never mind.  Should be my fault.  There is another similarly reported issue . Let me fix it ASAP. 

https://github.com/pmq20/ruby-compiler/issues/12#issuecomment-318420455

**Comment by pmq20** [comment] 2017-07-28 08:44
@ddoherty03 Weird. I failed to reproduce it locally in the latest master branch (i.e. 0.4.0). Which version of rubyc are you using?

**Comment by ddoherty03** [comment] 2017-07-31 08:33
@pmq20, I tried to get the version with `rubyc --version`, but it updated the version when I got that to 0.3.3.

Anyway, I tried again and go the same error:

```sh
-> Running [{"CI"=>"true", "PATH"=>"/tmp/rubyc/ruby-2.4.1-.3.0/build/bin:/home/ded/.rbenv/shims:/home/ded/.rbenv/bin:/home/ded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ded/.cask/bin:/home/ded/go/bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "sh", "-c", "gem install /__enclose_io_memfs__/local/vendor/bundler-1.15.2.gem --force --local --no-rdoc --no-ri"]
ERROR:  Could not find a valid gem '/__enclose_io_memfs__/local/vendor/bundler-1.15.2.gem' (>= 0) in any repository
Failed running [{"CI"=>"true", "PATH"=>"/tmp/rubyc/ruby-2.4.1-.3.0/build/bin:/home/ded/.rbenv/shims:/home/ded/.rbenv/bin:/home/ded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ded/.cask/bin:/home/ded/go/bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "sh", "-c", "gem install /__enclose_io_memfs__/local/vendor/bundler-1.15.2.gem --force --local --no-rdoc --no-ri"]

```

Here is the text of bin/byr:
```ruby
#! /usr/bin/env ruby
# -*- coding: utf-8 -*-
# -*- mode: ruby -*-

require 'byr'

module Byr
  if ['-l', '--ledger'].include?(ARGV[0])
    ARGV.shift
    ledger_name = ARGV.shift
  elsif ['-v', '--version'].include?(ARGV[0])
    puts Byr::VERSION
    exit(0)
  end

  command_name = ARGV.shift || 'shell'
  init unless command_name == 'init'
  set_current_ledger(ledger_name) if ledger_name

  command = Command.get(command_name)
  unless command
    raise UserError, "unknown command #{command_name}"
  end
  exit(command.run(ARGV, from_shell: false))

rescue => exception
  case exception
  when UserError
    oops "Error: #{exception.message}"
  else
    # Byr::LogicError, Byr::TransientError, and others
    oops "Logic Error: #{exception}"
    exception.backtrace.each do |ln|
      oops ln
    end
  end
  exit(1)
end
```
Is there anything else that would help you diagnose this?

**Comment by pmq20** [comment] 2017-07-31 08:36
@ddoherty03 I figured it out. `gem` cannot read a virtual path. The reason why it works from the `master` repo is that it is reading a real path. Let me fix it

**Comment by pmq20** [comment] 2017-07-31 08:39
Fixed in a84edb6

I'll release it in rubyc v0.4.0 as soon as possible.

**Comment by ddoherty03** [comment] 2017-07-31 14:33
Good work, @pmq20.  I'll try it out when I get some time.

**Comment by SwagDevOps** [comment] 2017-08-02 19:43
So impatient for ``rubyc v0.4.0``…  so bored to compile rubyc from sources (but it works).

**Comment by ddoherty03** [comment] 2017-08-02 20:22
@SwagDevOps. are you saying you have v0.4.0?  I don't see it yet.

**Comment by SwagDevOps** [comment] 2017-08-02 22:55
Absolutly… as said [previously](https://forum.ubuntu-fr.org/search.php?search_id=1929861226), bug is fixed since 3 days… but, ATM, you MUST compile ``rubyc`` from sources yourself (or wait for a release).

~~~~
# rubyc --version
0.4.0
# rubyc --help | head -2
Ruby Compiler (rubyc) v0.4.0
Compiling your Ruby application into a single executable.
~~~~

**Comment by pmq20** [comment] 2017-08-14 09:38
@ddoherty03 @SwagDevOps Ruby Compiler v0.4.0 released! Download: http://enclose.io/rubyc

**Comment by drbrain** [comment] 2018-05-09 23:14
Closing due to lack of feedback

**Closed by drbrain** 2018-05-09 23:14 UTC
