### ISSUE TITLE
Error while compiling rails app

### ISSUE THREAD

**Issue by novneetnov** [pmq20/ruby-packer#12] opened 2017-07-27 12:32 UTC
I am using ruby 2.3.3 with Rails 5.0.4
While trying to compile a rails app with` ./rubyc bin/rails` I ran into an error: 
```
In file included from ./curses.priv.h:325:0,
                 from ../ncurses/lib_gen.c:19:
_29511.c:843:15: error: expected ‘)’ before ‘int’
```
```
Makefile:962: recipe for target '../objects/lib_gen.o' failed
make[1]: *** [../objects/lib_gen.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/rubyc/ncurses/ncurses'
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
Failed running [{"CI"=>"true", "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "CFLAGS"=>" -fPIC -O3 -fno-fast-math -ggdb3 -Os -fdata-sections -ffunction-sections -pipe ", "LDFLAGS"=>""}, "make -j4"]
```
And the the output executable binary file was not created. Any light on this?

**Comment by pmq20** [comment] 2017-07-27 13:26
Interesting. This is due to a dependency-library failing to compile, i.e. `ncurses`. What is your compiler version? Maybe it's too old? You could Google it since this is about ncurses and not related directly to ruby or rubyc.

**Comment by novneetnov** [comment] 2017-07-27 16:49
Yeah. You are correct. This was an external error, which I seem to have fixed. But I have run into another error. 
```
ERROR:  Could not find a valid gem '/__enclose_io_memfs__/local/vendor/bundler-1.15.2.gem' (>= 0) in any repository
Failed running [{"CI"=>"true", "PATH"=>"/tmp/rubyc/ruby-2.4.1-0.3.0/build/bin:/home/novneet/.rvm/gems/ruby-2.3.3@rails5/bin:/home/novneet/.rvm/gems/ruby-2.3.3@global/bin:/home/novneet/.rvm/rubies/ruby-2.3.3/bin:/home/novneet/bin:/home/novneet/.local/bin:/home/novneet/.nvm/versions/node/v4.2.3/bin:/home/novneet/bin:/home/novneet/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/novneet/.rvm/bin:/snap/bin:/home/novneet/.rvm/bin:/home/novneet/.rvm/bin", "GEM_HOME"=>nil, "GEM_PATH"=>nil, "ENCLOSE_IO_USE_ORIGINAL_RUBY"=>"1", "ENCLOSE_IO_RUBYC_1ST_PASS"=>"1", "ENCLOSE_IO_RUBYC_2ND_PASS"=>nil}, "sh", "-c", "gem install /__enclose_io_memfs__/local/vendor/bundler-1.15.2.gem --force --local --no-rdoc --no-ri"]
```
I have bundler version 1.15.3. Do I need to downgrade it to v 1.15.2?  
Oh and you have not mentioned it the docs, but rubyc works fine with rvm right?

**Comment by pmq20** [comment] 2017-07-28 02:31
@novneetnov This is definitely my fault, since there is another similarly reported issue . Let me fix it ASAP.

https://github.com/pmq20/ruby-compiler/issues/11

**Comment by pmq20** [comment] 2017-07-28 08:37
@novneetnov Weird. I failed to reproduce it locally in the latest `master ` branch (i.e. `0.4.0`). Which version of `rubyc` are you using?

**Comment by novneetnov** [comment] 2017-07-28 08:46
@pmq20 I have downloaded rubyc by the following command:
`curl -L http://enclose.io/rubyc/rubyc-linux-x64.gz | gunzip > rubyc`
This get me the 0.3.0 version.
How do I get the latest version? Should I clone the master branch locally?

**Comment by pmq20** [comment] 2017-07-29 01:13
@novneetnov Yes, please coone the master branch and then execute from `bin/rubyc` to see if it is already fixed. I'll release the next version very soon. Thanks!

**Comment by pmq20** [comment] 2017-07-31 08:40
Fixed in a84edb6

I'll release it in rubyc v0.4.0 as soon as possible.

**Comment by obromios** [comment] 2017-07-31 10:26
I have the same problem, look forward to ruby v0.4.0

**Comment by pmq20** [comment] 2017-08-14 09:39
@novneetnov @obromios  Ruby Compiler v0.4.0 released! Download: http://enclose.io/rubyc

**Comment by obromios** [comment] 2017-08-30 07:34
I downloaded the latest version and checked that ```./rubyc --version``` gives 0.4.0. I am no longer getting the error above, but I get a few problems. 

The first is a warning 'The latest bundler is 1.15.4, but you are currently running 1.15.3'.   This is puzzling because I am using 1.15.4, and do not have 1.15.3 installed. As well, in the output of the rubyc it actually says it is installing 1.15.3.

Second, there appears to be a fatal error 'Your Ruby version is 2.4.1, but your Gemfile specified 2.2.7
Failed Running...'
Do I need to upgrade to ruby 2.4.1 to use rubyc?

As a sanity check, I ran rubyc on a  'hello world' ruby file.
```
#!/usr/bin/env ruby
puts 'Hello World'
```
This also failed, with the error

```
/__enclose_io_memfs__/local/lib/compiler.rb:678:in `binread': Invalid argument @ io_fread - enclose_io_memfs.squashfs (Errno::EINVAL)
	from /__enclose_io_memfs__/local/lib/compiler.rb:678:in `block in make_enclose_io_memfs'
	from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `block in chdir'
	from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
	from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
	from /__enclose_io_memfs__/local/lib/compiler.rb:673:in `make_enclose_io_memfs'
	from /__enclose_io_memfs__/local/lib/compiler.rb:485:in `block in run!'
	from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `block in chdir'
	from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
	from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
	from /__enclose_io_memfs__/local/lib/compiler.rb:365:in `run!'
	from /__enclose_io_memfs__/local/bin/rubyc:149:in `<main>'
```

**Comment by pmq20** [comment] 2017-08-31 01:37
@obromios Regarding the sanity check, it looks as though `enclose_io_memfs.squashfs` does not exist. Could you paste more log so that I can inspect about the generating of `enclose_io_memfs.squashfs`?

**Comment by drbrain** [comment] 2018-05-09 23:13
Closing due to lack of response.

**Closed by drbrain** 2018-05-09 23:13 UTC

**Comment by iamsimakov** [comment] 2018-05-26 19:51
error about ncurses fixed by
`export CPPFLAGS="-P"`

**Comment by Githubsectest** [comment] 2019-12-13 05:02
> @obromios Regarding the sanity check, it looks as though `enclose_io_memfs.squashfs` does not exist. Could you paste more log so that I can inspect about the generating of `enclose_io_memfs.squashfs`?

-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/utf_16le.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/utf_32be.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/utf_32le.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/windows_31j.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/windows_1250.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/windows_1251.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/windows_1252.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/windows_1253.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/windows_1254.so
-> rm -f /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/lib/ruby/2.4.0/x86_64-linux/enc/windows_1257.so
-> cd /opt/rubyc
-> cp -r "/opt/rubyc" "/tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/local"
-> cd /tmp/rubyc/rubyc_work_dir/__enclose_io_memfs__/local
-> cd bin
/__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir': No such file or directory @ dir_chdir - bin (Errno::ENOENT)
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
        from /__enclose_io_memfs__/local/lib/compiler.rb:645:in `block (2 levels) in prepare_local'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `block in chdir'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
        from /__enclose_io_memfs__/local/lib/compiler.rb:635:in `block in prepare_local'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `block in chdir'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
        from /__enclose_io_memfs__/local/lib/compiler.rb:527:in `prepare_local'
        from /__enclose_io_memfs__/local/lib/compiler.rb:464:in `block in run!'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `block in chdir'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
        from /__enclose_io_memfs__/local/lib/compiler/utils.rb:45:in `chdir'
        from /__enclose_io_memfs__/local/lib/compiler.rb:365:in `run!'
        from /__enclose_io_memfs__/local/bin/rubyc:149:in `<main>'
